name: GithubDemo
on:
  push:
    branches:
      - master

env:
  GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
  WORKSPACE: ${{ github.workspace }}
  REPONAME: ${{ github.event.repository.name }}

jobs:
  Build_Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: "true"
          ref: "master"
          token: ${{ env.GITHUB_PAT }}

      - name: Build
        run: |
          set -e
          mvn package -Dmaven.test.skip=true

      - name: Deployment
        run: |
          set -ex
          cd ${WORKSPACE}
          echo "${{ secrets.SSH_KEY }}" > ssh_key.pem
          scp -i ssh_key.pem /home/runner/work/PetClinic/PetClinic/target/petclinic.war root@13.201.132.49:/opt/apache-tomcat-8.5.99/webapps/
          ssh -i ssh_key.pem root@13.201.132.49 'nohup /opt/apache-tomcat-8.5.99/bin/catalina.sh start'
